version: "3.8"

services:
  tv_redirector:
    build: .
    container_name: tv_redirector
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////app/tv.db

  caddy:
    image: caddy:alpine
    container_name: tv_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    depends_on:
      - tv_redirector

volumes:
  caddy_data:
  caddy_config:
